### ISSUE TITLE
[TASK] Protect backend for phone number verified users

### ISSUE THREAD

**Issue by fdhenard** [rokwire/rokwire-building-blocks-api#85]
### Description
Need to figure out how to protect endpoints for phone number verified users.  Planning to discuss with Jeff Gaynor

### Acceptance Criteria
plan for implementation is ready

### TODO
- [x] Initial discussion with Jeff Gaynor
- [x] build an auth service (building block) that only includes phone number verification (integrated with Twilio)
- [x] document usage from client apps
    - [x] update rokwire.yaml swagger docs
    - [x] document usage of authservice in readme.md
- [x] pull request change requests resolved, and pull request merged
